const graph = [
  {
    nodes: [
      { id: "A", group: 1, value: 1 },
      { id: "B", group: 1, value: 3 },
      { id: "C", group: 1, value: 5 },
      { id: "D", group: 2, value: 7 },
      { id: "E", group: 2, value: 4 },
      { id: "F", group: 3, value: 6 },
      { id: "G", group: 3, value: 2 },
      { id: "H", group: 4, value: 4 },
      { id: "I", group: 4, value: 8 },
      { id: "J", group: 5, value: 6 },
      { id: "K", group: 4, value: 5 },
    ],
    links: [
      { source: "A", target: "B", value: 8 },
      { source: "C", target: "D", value: 2 },
      { source: "A", target: "C", value: 2 },
      { source: "B", target: "D", value: 4 },
      { source: "A", target: "E", value: 6 },
      { source: "A", target: "F", value: 2 },
      { source: "C", target: "F", value: 1 },
      { source: "G", target: "F", value: 1 },
      { source: "G", target: "H", value: 8 },
      { source: "F", target: "I", value: 2 },
      { source: "H", target: "J", value: 3 },
      { source: "I", target: "J", value: 4 },
      { source: "J", target: "K", value: 5 },
    ],
  },
  [
    { id: "A", attr: "a", value: 1 },
    { id: "A", attr: "b", value: 0 },
    { id: "A", attr: "c", value: 3 },
    { id: "A", attr: "d", value: 2 },
    { id: "A", attr: "e", value: 5 },
    { id: "A", attr: "f", value: 1 },
    { id: "A", attr: "g", value: 0 },
    { id: "B", attr: "a", value: 3 },
    { id: "B", attr: "b", value: 4 },
    { id: "B", attr: "c", value: 2 },
    { id: "B", attr: "d", value: 4 },
    { id: "B", attr: "e", value: 1 },
    { id: "B", attr: "f", value: 5 },
    { id: "B", attr: "g", value: 0 },
    { id: "B", attr: "a", value: 2 },
    { id: "C", attr: "a", value: 1 },
    { id: "C", attr: "b", value: 0 },
    { id: "C", attr: "c", value: 3 },
    { id: "C", attr: "d", value: 2 },
    { id: "C", attr: "e", value: 5 },
    { id: "C", attr: "f", value: 1 },
    { id: "C", attr: "g", value: 0 },
    { id: "D", attr: "a", value: 3 },
    { id: "D", attr: "b", value: 4 },
    { id: "D", attr: "c", value: 2 },
    { id: "D", attr: "d", value: 4 },
    { id: "D", attr: "e", value: 1 },
    { id: "D", attr: "f", value: 5 },
    { id: "D", attr: "g", value: 0 },
    { id: "D", attr: "a", value: 2 },
    { id: "E", attr: "a", value: 3 },
    { id: "E", attr: "b", value: 4 },
    { id: "E", attr: "c", value: 2 },
    { id: "E", attr: "d", value: 5 },
    { id: "E", attr: "e", value: 6 },
    { id: "E", attr: "f", value: 4 },
    { id: "E", attr: "g", value: 2 },
    { id: "F", attr: "a", value: 3 },
    { id: "F", attr: "b", value: 4 },
    { id: "F", attr: "c", value: 1 },
    { id: "F", attr: "d", value: 0 },
    { id: "F", attr: "e", value: 0 },
    { id: "F", attr: "f", value: 5 },
    { id: "F", attr: "g", value: 2 },
    { id: "G", attr: "a", value: 3 },
    { id: "G", attr: "b", value: 4 },
    { id: "G", attr: "c", value: 2 },
    { id: "G", attr: "d", value: 5 },
    { id: "G", attr: "e", value: 6 },
    { id: "G", attr: "f", value: 4 },
    { id: "G", attr: "g", value: 2 },
    { id: "K", attr: "a", value: 3 },
    { id: "K", attr: "b", value: 4 },
    { id: "K", attr: "c", value: 1 },
    { id: "K", attr: "d", value: 0 },
    { id: "K", attr: "e", value: 0 },
    { id: "K", attr: "f", value: 5 },
    { id: "K", attr: "g", value: 2 },
  ],
];

export default graph;
