const target_data = [
  {
    id: "junas_kinase",
    label: "Junas Kinase",
    img_path: "src/target_img/Janus_kinase.png",
    tree: [
      { name: "1", parents: [], children: ["2", "3"] },
      { name: "2", parents: ["1"], children: ["4"] },
      { name: "3", parents: ["1"], children: ["9", "10", "11"] },
    ],
    heatsquaredata: [
      { label: "A", hvalue: 5, svalue: 5 },
      { label: "B", hvalue: 4, svalue: 3 },
      { label: "C", hvalue: 3, svalue: 2 },
      { label: "D", hvalue: 6, svalue: 4 },
      { label: "E", hvalue: 1, svalue: 6 },
      { label: "F", hvalue: 2, svalue: 7 },
      { label: "G", hvalue: 3, svalue: 5 },
      { label: "H", hvalue: 5, svalue: 8 },
      { label: "I", hvalue: 7, svalue: 1 },
      { label: "J", hvalue: 4, svalue: 3 },
      { label: "K", hvalue: 8, svalue: 5 },
      { label: "L", hvalue: 4, svalue: 9 },
      { label: "M", hvalue: 5, svalue: 5 },
      { label: "N", hvalue: 2, svalue: 4 },
    ],
    stackedareadata: [
      {
        year: 2015,
        A: 13300,
        B: 21000,
        C: 12000,
      },
      {
        year: 2016,
        A: 32300,
        B: 42400,
        C: 21200,
      },
      {
        year: 2017,
        A: 30003,
        B: 34020,
        C: 15010,
      },
      {
        year: 2018,
        A: 12300,
        B: 22000,
        C: 11000,
      },
      {
        year: 2019,
        A: 22300,
        B: 22400,
        C: 11200,
      },
      {
        year: 2020,
        A: 12003,
        B: 20020,
        C: 10010,
      },
    ],
    detaildata: [
      {
        nodes: [
          { id: "A", group: 1, value: 1 },
          { id: "B", group: 1, value: 3 },
          { id: "C", group: 1, value: 5 },
          { id: "D", group: 2, value: 7 },
          { id: "E", group: 2, value: 4 },
          { id: "F", group: 3, value: 6 },
          { id: "G", group: 3, value: 2 },
          { id: "H", group: 4, value: 4 },
          { id: "I", group: 4, value: 8 },
          { id: "J", group: 5, value: 6 },
          { id: "K", group: 4, value: 5 },
        ],
        links: [
          { source: "A", target: "B", value: 8 },
          { source: "C", target: "D", value: 2 },
          { source: "A", target: "C", value: 2 },
          { source: "B", target: "D", value: 4 },
          { source: "A", target: "E", value: 6 },
          { source: "A", target: "F", value: 2 },
          { source: "C", target: "F", value: 1 },
          { source: "G", target: "F", value: 1 },
          { source: "G", target: "H", value: 8 },
          { source: "F", target: "I", value: 2 },
          { source: "H", target: "J", value: 3 },
          { source: "I", target: "J", value: 4 },
          { source: "J", target: "K", value: 5 },
        ],
      },
      [
        { id: "A", attr: "a", value: 1 },
        { id: "A", attr: "b", value: 0 },
        { id: "A", attr: "c", value: 3 },
        { id: "A", attr: "d", value: 2 },
        { id: "A", attr: "e", value: 5 },
        { id: "A", attr: "f", value: 1 },
        { id: "A", attr: "g", value: 0 },
        { id: "B", attr: "a", value: 3 },
        { id: "B", attr: "b", value: 4 },
        { id: "B", attr: "c", value: 2 },
        { id: "B", attr: "d", value: 4 },
        { id: "B", attr: "e", value: 1 },
        { id: "B", attr: "f", value: 5 },
        { id: "B", attr: "g", value: 0 },
        { id: "C", attr: "a", value: 1 },
        { id: "C", attr: "b", value: 0 },
        { id: "C", attr: "c", value: 3 },
        { id: "C", attr: "d", value: 2 },
        { id: "C", attr: "e", value: 5 },
        { id: "C", attr: "f", value: 1 },
        { id: "C", attr: "g", value: 0 },
        { id: "D", attr: "a", value: 3 },
        { id: "D", attr: "b", value: 4 },
        { id: "D", attr: "c", value: 2 },
        { id: "D", attr: "d", value: 4 },
        { id: "D", attr: "e", value: 1 },
        { id: "D", attr: "f", value: 5 },
        { id: "D", attr: "g", value: 0 },
        { id: "E", attr: "a", value: 3 },
        { id: "E", attr: "b", value: 4 },
        { id: "E", attr: "c", value: 2 },
        { id: "E", attr: "d", value: 5 },
        { id: "E", attr: "e", value: 6 },
        { id: "E", attr: "f", value: 4 },
        { id: "E", attr: "g", value: 2 },
        { id: "F", attr: "a", value: 3 },
        { id: "F", attr: "b", value: 4 },
        { id: "F", attr: "c", value: 1 },
        { id: "F", attr: "d", value: 0 },
        { id: "F", attr: "e", value: 0 },
        { id: "F", attr: "f", value: 5 },
        { id: "F", attr: "g", value: 2 },
        { id: "G", attr: "a", value: 3 },
        { id: "G", attr: "b", value: 4 },
        { id: "G", attr: "c", value: 2 },
        { id: "G", attr: "d", value: 5 },
        { id: "G", attr: "e", value: 6 },
        { id: "G", attr: "f", value: 4 },
        { id: "G", attr: "g", value: 2 },
        { id: "K", attr: "a", value: 3 },
        { id: "K", attr: "b", value: 4 },
        { id: "K", attr: "c", value: 1 },
        { id: "K", attr: "d", value: 0 },
        { id: "K", attr: "e", value: 0 },
        { id: "K", attr: "f", value: 5 },
        { id: "K", attr: "g", value: 2 },
      ],
      [
        { id: "A", attr: "a", value: 1 },
        { id: "A", attr: "b", value: 0 },
        { id: "A", attr: "c", value: 3 },
        { id: "A", attr: "d", value: 1 },
        { id: "A", attr: "e", value: 5 },
        { id: "C", attr: "a", value: 1 },
        { id: "C", attr: "b", value: 0 },
        { id: "C", attr: "c", value: 1 },
        { id: "C", attr: "d", value: 2 },
        { id: "C", attr: "e", value: 0 },
        { id: "D", attr: "a", value: 3 },
        { id: "D", attr: "b", value: 4 },
        { id: "D", attr: "c", value: 2 },
        { id: "D", attr: "d", value: 4 },
        { id: "D", attr: "e", value: 1 },
        { id: "G", attr: "a", value: 0 },
        { id: "G", attr: "b", value: 5 },
        { id: "G", attr: "c", value: 2 },
        { id: "G", attr: "d", value: 3 },
        { id: "G", attr: "e", value: 0 },
        { id: "K", attr: "a", value: 3 },
        { id: "K", attr: "b", value: 0 },
        { id: "K", attr: "c", value: 1 },
        { id: "K", attr: "d", value: 0 },
        { id: "K", attr: "e", value: 0 },
      ],
    ],
  },
  {
    id: "stat3",
    label: "STAT3",
    img_path: "./logo.svg",
    tree: [
      { name: "5", parents: [], children: ["6"] },
      { name: "6", parents: ["5"], children: ["7", "8"] },
    ],
    heatsquaredata: [
      { label: "A", hvalue: 5, svalue: 4 },
      { label: "B", hvalue: 4, svalue: 6 },
      { label: "C", hvalue: 3, svalue: 7 },
      { label: "D", hvalue: 6, svalue: 4 },
      { label: "E", hvalue: 1, svalue: 5 },
      { label: "F", hvalue: 2, svalue: 2 },
      { label: "G", hvalue: 3, svalue: 3 },
      { label: "H", hvalue: 5, svalue: 8 },
      { label: "I", hvalue: 7, svalue: 6 },
      { label: "J", hvalue: 4, svalue: 3 },
      { label: "K", hvalue: 8, svalue: 4 },
      { label: "L", hvalue: 4, svalue: 6 },
      { label: "M", hvalue: 5, svalue: 5 },
      { label: "N", hvalue: 2, svalue: 6 },
    ],
    stackedareadata: [
      {
        year: 2015,
        A: 13300,
        B: 21000,
        C: 12000,
      },
      {
        year: 2016,
        A: 32300,
        B: 42400,
        C: 21200,
      },
      {
        year: 2017,
        A: 30003,
        B: 34020,
        C: 15010,
      },
      {
        year: 2018,
        A: 12300,
        B: 22000,
        C: 11000,
      },
      {
        year: 2019,
        A: 22300,
        B: 22400,
        C: 11200,
      },
      {
        year: 2020,
        A: 12003,
        B: 20020,
        C: 10010,
      },
    ],
  },
  {
    id: "a",
    label: "a",
    img_path: "./logo.svg",
    tree: [
      { name: "2", parents: ["1"], children: ["4"] },
      { name: "4", parents: ["2"], children: [] },
    ],
    heatsquaredata: [
      { label: "A", hvalue: 5, svalue: 2 },
      { label: "B", hvalue: 4, svalue: 1 },
      { label: "C", hvalue: 3, svalue: 4 },
      { label: "D", hvalue: 6, svalue: 5 },
      { label: "E", hvalue: 1, svalue: 3 },
      { label: "F", hvalue: 2, svalue: 5 },
      { label: "G", hvalue: 3, svalue: 8 },
      { label: "H", hvalue: 5, svalue: 5 },
      { label: "I", hvalue: 7, svalue: 4 },
      { label: "J", hvalue: 4, svalue: 5 },
      { label: "K", hvalue: 8, svalue: 2 },
      { label: "L", hvalue: 4, svalue: 3 },
      { label: "M", hvalue: 5, svalue: 1 },
      { label: "N", hvalue: 2, svalue: 5 },
    ],
    stackedareadata: [
      {
        year: 2015,
        A: 13300,
        B: 21000,
        C: 12000,
      },
      {
        year: 2016,
        A: 32300,
        B: 42400,
        C: 21200,
      },
      {
        year: 2017,
        A: 30003,
        B: 34020,
        C: 15010,
      },
      {
        year: 2018,
        A: 12300,
        B: 22000,
        C: 11000,
      },
      {
        year: 2019,
        A: 22300,
        B: 22400,
        C: 11200,
      },
      {
        year: 2020,
        A: 12003,
        B: 20020,
        C: 10010,
      },
    ],
  },
  {
    id: "b",
    label: "b",
    img_path: "./logo.svg",
    tree: [
      { name: "6", parents: ["5"], children: ["7", "8"] },
      { name: "7", parents: ["6"], children: [] },
      { name: "8", parents: ["6"], children: [] },
    ],
    heatsquaredata: [
      { label: "A", hvalue: 5, svalue: 3 },
      { label: "B", hvalue: 4, svalue: 4 },
      { label: "C", hvalue: 3, svalue: 5 },
      { label: "D", hvalue: 6, svalue: 6 },
      { label: "E", hvalue: 1, svalue: 2 },
      { label: "F", hvalue: 2, svalue: 4 },
      { label: "G", hvalue: 3, svalue: 6 },
      { label: "H", hvalue: 5, svalue: 4 },
      { label: "I", hvalue: 7, svalue: 5 },
      { label: "J", hvalue: 4, svalue: 3 },
      { label: "K", hvalue: 8, svalue: 4 },
      { label: "L", hvalue: 4, svalue: 3 },
      { label: "M", hvalue: 5, svalue: 6 },
      { label: "N", hvalue: 2, svalue: 4 },
    ],
    stackedareadata: [
      {
        year: 2015,
        A: 13300,
        B: 21000,
        C: 12000,
      },
      {
        year: 2016,
        A: 32300,
        B: 42400,
        C: 21200,
      },
      {
        year: 2017,
        A: 30003,
        B: 34020,
        C: 15010,
      },
      {
        year: 2018,
        A: 12300,
        B: 22000,
        C: 11000,
      },
      {
        year: 2019,
        A: 22300,
        B: 22400,
        C: 11200,
      },
      {
        year: 2020,
        A: 12003,
        B: 20020,
        C: 10010,
      },
    ],
  },
  {
    id: "c",
    label: "c",
    img_path: "./logo.svg",
    tree: [
      { name: "3", parents: ["1"], children: ["9", "10", "11"] },
      { name: "9", parents: ["3"], children: [] },
      { name: "10", parents: ["3"], children: [] },
    ],
    heatsquaredata: [
      { label: "A", hvalue: 5, svalue: 4 },
      { label: "B", hvalue: 4, svalue: 3 },
      { label: "C", hvalue: 3, svalue: 5 },
      { label: "D", hvalue: 6, svalue: 7 },
      { label: "E", hvalue: 1, svalue: 4 },
      { label: "F", hvalue: 2, svalue: 3 },
      { label: "G", hvalue: 3, svalue: 2 },
      { label: "H", hvalue: 5, svalue: 5 },
      { label: "I", hvalue: 7, svalue: 7 },
      { label: "J", hvalue: 4, svalue: 8 },
      { label: "K", hvalue: 8, svalue: 9 },
      { label: "L", hvalue: 4, svalue: 5 },
      { label: "M", hvalue: 5, svalue: 3 },
      { label: "N", hvalue: 2, svalue: 5 },
    ],
    stackedareadata: [
      {
        year: 2015,
        A: 13300,
        B: 21000,
        C: 12000,
      },
      {
        year: 2016,
        A: 32300,
        B: 42400,
        C: 21200,
      },
      {
        year: 2017,
        A: 30003,
        B: 34020,
        C: 15010,
      },
      {
        year: 2018,
        A: 12300,
        B: 22000,
        C: 11000,
      },
      {
        year: 2019,
        A: 22300,
        B: 22400,
        C: 11200,
      },
      {
        year: 2020,
        A: 12003,
        B: 20020,
        C: 10010,
      },
    ],
  },
  {
    id: "d",
    label: "d",
    img_path: "./logo.svg",
    tree: [
      { name: "3", parents: ["1"], children: ["9", "10", "11"] },
      { name: "11", parents: ["3"], children: ["12"] },
      { name: "12", parents: ["11"], children: [] },
    ],
    heatsquaredata: [
      { label: "A", hvalue: 5, svalue: 2 },
      { label: "B", hvalue: 4, svalue: 4 },
      { label: "C", hvalue: 3, svalue: 5 },
      { label: "D", hvalue: 6, svalue: 6 },
      { label: "E", hvalue: 1, svalue: 4 },
      { label: "F", hvalue: 2, svalue: 8 },
      { label: "G", hvalue: 3, svalue: 3 },
      { label: "H", hvalue: 5, svalue: 4 },
      { label: "I", hvalue: 7, svalue: 5 },
      { label: "J", hvalue: 4, svalue: 1 },
      { label: "K", hvalue: 8, svalue: 3 },
      { label: "L", hvalue: 4, svalue: 2 },
      { label: "M", hvalue: 5, svalue: 5 },
      { label: "N", hvalue: 2, svalue: 5 },
    ],
    stackedareadata: [
      {
        year: 2015,
        A: 13300,
        B: 21000,
        C: 12000,
      },
      {
        year: 2016,
        A: 32300,
        B: 42400,
        C: 21200,
      },
      {
        year: 2017,
        A: 30003,
        B: 34020,
        C: 15010,
      },
      {
        year: 2018,
        A: 12300,
        B: 22000,
        C: 11000,
      },
      {
        year: 2019,
        A: 22300,
        B: 22400,
        C: 11200,
      },
      {
        year: 2020,
        A: 12003,
        B: 20020,
        C: 10010,
      },
    ],
  },
];

export default target_data;
