const target_data = [
  {
    id: "junas_kinase",
    label: "Junas Kinase",
    img_path: "src/target_img/Janus_kinase.png",
    tree: [
      { name: "1", parents: [], children: ["2", "3"] },
      { name: "2", parents: ["1"], children: ["4"] },
      { name: "3", parents: ["1"], children: ["9", "10", "11"] },
    ],
    heatsquaredata: [
      {
        label: "A",
        hvalue: 5,
        svalue: 5,
        line: [
          { value: 3, pub: 5 },
          { value: 4, pub: 6 },
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
        ],
      },
      {
        label: "B",
        hvalue: 4,
        svalue: 3,
        line: [
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
          { value: 9, pub: 3 },
          { value: 10, pub: 2 },
        ],
      },
      {
        label: "C",
        hvalue: 3,
        svalue: 2,
        line: [
          { value: 4, pub: 6 },
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
          { value: 9, pub: 3 },
          { value: 10, pub: 2 },
        ],
      },
      {
        label: "D",
        hvalue: 6,
        svalue: 4,
        line: [
          { value: 3, pub: 5 },
          { value: 4, pub: 6 },
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
        ],
      },
      {
        label: "E",
        hvalue: 1,
        svalue: 6,
        line: [
          { value: 4, pub: 6 },
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
          { value: 9, pub: 3 },
        ],
      },
      {
        label: "F",
        hvalue: 2,
        svalue: 7,
        line: [
          { value: 3, pub: 5 },
          { value: 4, pub: 7 },
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 12 },
          { value: 8, pub: 4 },
          { value: 9, pub: 3 },
          { value: 10, pub: 2 },
        ],
      },
      {
        label: "G",
        hvalue: 3,
        svalue: 5,
        line: [
          { value: 3, pub: 5 },
          { value: 4, pub: 7 },
          { value: 5, pub: 10 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
        ],
      },
      {
        label: "H",
        hvalue: 5,
        svalue: 8,
        line: [
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
          { value: 9, pub: 3 },
          { value: 10, pub: 2 },
        ],
      },
      {
        label: "I",
        hvalue: 7,
        svalue: 1,
        line: [
          { value: 3, pub: 5 },
          { value: 4, pub: 6 },
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
          { value: 9, pub: 3 },
          { value: 10, pub: 2 },
        ],
      },
      {
        label: "J",
        hvalue: 4,
        svalue: 3,
        line: [
          { value: 3, pub: 5 },
          { value: 4, pub: 6 },
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
          { value: 9, pub: 3 },
        ],
      },
      {
        label: "K",
        hvalue: 8,
        svalue: 5,
        line: [
          { value: 4, pub: 6 },
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
          { value: 9, pub: 3 },
          { value: 10, pub: 2 },
        ],
      },
      {
        label: "L",
        hvalue: 4,
        svalue: 9,
        line: [
          { value: 3, pub: 5 },
          { value: 4, pub: 6 },
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
          { value: 9, pub: 3 },
          { value: 10, pub: 2 },
        ],
      },
      {
        label: "M",
        hvalue: 5,
        svalue: 5,
        line: [
          { value: 3, pub: 5 },
          { value: 4, pub: 6 },
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
          { value: 9, pub: 3 },
          { value: 10, pub: 2 },
        ],
      },
      {
        label: "N",
        hvalue: 2,
        svalue: 4,
        line: [
          { value: 3, pub: 5 },
          { value: 4, pub: 6 },
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
          { value: 9, pub: 3 },
          { value: 10, pub: 2 },
        ],
      },
      {
        label: "O",
        hvalue: 5,
        svalue: 5,
        line: [
          { value: 3, pub: 5 },
          { value: 4, pub: 6 },
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
          { value: 9, pub: 3 },
          { value: 10, pub: 2 },
        ],
      },
      {
        label: "P",
        hvalue: 2,
        svalue: 4,
        line: [
          { value: 3, pub: 5 },
          { value: 4, pub: 6 },
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
          { value: 9, pub: 3 },
          { value: 10, pub: 2 },
        ],
      },
      {
        label: "Q",
        hvalue: 5,
        svalue: 5,
        line: [
          { value: 3, pub: 5 },
          { value: 4, pub: 6 },
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
          { value: 9, pub: 3 },
          { value: 10, pub: 2 },
        ],
      },
      {
        label: "R",
        hvalue: 2,
        svalue: 4,
        line: [
          { value: 3, pub: 5 },
          { value: 4, pub: 6 },
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
          { value: 9, pub: 3 },
          { value: 10, pub: 2 },
        ],
      },
      {
        label: "S",
        hvalue: 5,
        svalue: 5,
        line: [
          { value: 3, pub: 5 },
          { value: 4, pub: 6 },
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
          { value: 9, pub: 3 },
          { value: 10, pub: 2 },
        ],
      },
    ],
    stackedareadata: [
      {
        year: 2015,
        A: 13300,
        B: 21000,
        C: 12000,
      },
      {
        year: 2016,
        A: 32300,
        B: 42400,
        C: 21200,
      },
      {
        year: 2017,
        A: 30003,
        B: 34020,
        C: 15010,
      },
      {
        year: 2018,
        A: 12300,
        B: 22000,
        C: 11000,
      },
      {
        year: 2019,
        A: 22300,
        B: 22400,
        C: 11200,
      },
      {
        year: 2020,
        A: 12003,
        B: 20020,
        C: 10010,
      },
    ],
    detaildata: [
      {
        nodes: [
          { id: "A", group: 1, value: 1 },
          { id: "B", group: 1, value: 3 },
          { id: "C", group: 1, value: 5 },
          { id: "D", group: 2, value: 7 },
          { id: "E", group: 2, value: 4 },
          { id: "F", group: 3, value: 6 },
          { id: "G", group: 3, value: 2 },
          { id: "H", group: 4, value: 4 },
          { id: "I", group: 4, value: 8 },
          { id: "J", group: 5, value: 6 },
          { id: "K", group: 4, value: 5 },
        ],
        links: [
          { source: "A", target: "B", value: 8 },
          { source: "C", target: "D", value: 2 },
          { source: "A", target: "C", value: 2 },
          { source: "B", target: "D", value: 4 },
          { source: "A", target: "E", value: 6 },
          { source: "A", target: "F", value: 2 },
          { source: "C", target: "F", value: 1 },
          { source: "G", target: "F", value: 1 },
          { source: "G", target: "H", value: 8 },
          { source: "F", target: "I", value: 2 },
          { source: "H", target: "J", value: 3 },
          { source: "I", target: "J", value: 4 },
          { source: "J", target: "K", value: 5 },
        ],
      },
      [
        { id: "A", attr: "IC50", value: 1 },
        { id: "A", attr: "Ki", value: 0 },
        { id: "A", attr: "Kd", value: 3 },
        { id: "A", attr: "EC50", value: 2 },
        { id: "A", attr: "se", value: 5 },
        { id: "A", attr: "hERG", value: 1 },
        { id: "A", attr: "sol", value: 0 },
        { id: "B", attr: "IC50", value: 3 },
        { id: "B", attr: "Ki", value: 4 },
        { id: "B", attr: "Kd", value: 2 },
        { id: "B", attr: "EC50", value: 4 },
        { id: "B", attr: "se", value: 1 },
        { id: "B", attr: "hERG", value: 5 },
        { id: "B", attr: "sol", value: 0 },
        { id: "C", attr: "IC50", value: 1 },
        { id: "C", attr: "Ki", value: 0 },
        { id: "C", attr: "Kd", value: 3 },
        { id: "C", attr: "EC50", value: 2 },
        { id: "C", attr: "se", value: 5 },
        { id: "C", attr: "hERG", value: 1 },
        { id: "C", attr: "sol", value: 0 },
        { id: "D", attr: "IC50", value: 3 },
        { id: "D", attr: "Ki", value: 4 },
        { id: "D", attr: "Kd", value: 2 },
        { id: "D", attr: "EC50", value: 4 },
        { id: "D", attr: "se", value: 1 },
        { id: "D", attr: "hERG", value: 5 },
        { id: "D", attr: "sol", value: 0 },
        { id: "E", attr: "IC50", value: 3 },
        { id: "E", attr: "Ki", value: 4 },
        { id: "E", attr: "Kd", value: 2 },
        { id: "E", attr: "EC50", value: 5 },
        { id: "E", attr: "se", value: 6 },
        { id: "E", attr: "hERG", value: 4 },
        { id: "E", attr: "sol", value: 2 },
        { id: "F", attr: "IC50", value: 3 },
        { id: "F", attr: "Ki", value: 4 },
        { id: "F", attr: "Kd", value: 1 },
        { id: "F", attr: "EC50", value: 0 },
        { id: "F", attr: "se", value: 0 },
        { id: "F", attr: "hERG", value: 5 },
        { id: "F", attr: "sol", value: 2 },
        { id: "G", attr: "IC50", value: 3 },
        { id: "G", attr: "Ki", value: 4 },
        { id: "G", attr: "Kd", value: 2 },
        { id: "G", attr: "EC50", value: 5 },
        { id: "G", attr: "se", value: 6 },
        { id: "G", attr: "hERG", value: 4 },
        { id: "G", attr: "sol", value: 2 },
        { id: "K", attr: "IC50", value: 3 },
        { id: "K", attr: "Ki", value: 4 },
        { id: "K", attr: "Kd", value: 1 },
        { id: "K", attr: "EC50", value: 0 },
        { id: "K", attr: "se", value: 0 },
        { id: "K", attr: "hERG", value: 5 },
        { id: "K", attr: "sol", value: 2 },
      ],
      [
        { id: "A", attr: "ED50", value: 1 },
        { id: "A", attr: "t_half", value: 0 },
        { id: "A", attr: "AUC", value: 3 },
        { id: "A", attr: "bio", value: 1 },
        { id: "A", attr: "sol", value: 5 },
        { id: "C", attr: "ED50", value: 1 },
        { id: "C", attr: "t_half", value: 0 },
        { id: "C", attr: "AUC", value: 1 },
        { id: "C", attr: "bio", value: 2 },
        { id: "C", attr: "sol", value: 0 },
        { id: "D", attr: "ED50", value: 3 },
        { id: "D", attr: "t_half", value: 4 },
        { id: "D", attr: "AUC", value: 2 },
        { id: "D", attr: "bio", value: 4 },
        { id: "D", attr: "sol", value: 1 },
        { id: "G", attr: "ED50", value: 0 },
        { id: "G", attr: "t_half", value: 5 },
        { id: "G", attr: "AUC", value: 2 },
        { id: "G", attr: "bio", value: 3 },
        { id: "G", attr: "sol", value: 0 },
        { id: "K", attr: "ED50", value: 3 },
        { id: "K", attr: "t_half", value: 0 },
        { id: "K", attr: "AUC", value: 1 },
        { id: "K", attr: "bio", value: 0 },
        { id: "K", attr: "sol", value: 0 },
      ],
    ],
    sankeydata: [
      {
        name: "A",
        data: {
          p1_company_num: 8,
          p1_stat_company_num: [0, 0, 0, 3, 0, 0, 5, 0, 0],
          p1_company: [
            [],
            [],
            [],
            [
              "Barts Cancer Center, Barts and The London School of Medicine and Denistry",
              "UCSD Morres Cancer Center",
              "Tennessee Oncology",
            ],
            [],
            [],
            [
              "MedImmune LLC",
              "The University of Texas MD Anderson Cancer Center",
              "M.D. Anderson Cancer Center",
              "AstraZeneca",
              "National Cancer Institute (NCI)",
            ],
            [],
            [],
          ],
          p2_company_num: 3,
          p2_stat_company_num: [0, 1, 0, 1, 0, 1, 0, 0, 0],
          p2_company: [
            [],
            ["The University of Texas MD Anderson Cancer Center"],
            [],
            [],
            [],
            ["National Cancer Institute (NCI)"],
            ["M.D. Anderson Cancer Center"],
            [],
            [],
          ],
          p3_company_num: 1,
          p3_stat_company_num: [0, 1, 0, 0, 0, 0, 0, 0, 0],
          p3_company: [
            [],
            ["M.D. Anderson Cancer Center"],
            [],
            [],
            [],
            [],
            [],
            [],
            [],
          ],
        },
      },
      {
        name: "D",
        data: {
          p1_company_num: 8,
          p1_stat_company_num: [0, 0, 0, 3, 0, 0, 5, 0, 0],
          p1_company: [
            [],
            [],
            [],
            [
              "Barts Cancer Center, Barts and The London School of Medicine and Denistry",
              "UCSD Morres Cancer Center",
              "Tennessee Oncology",
            ],
            [],
            [],
            [
              "MedImmune LLC",
              "The University of Texas MD Anderson Cancer Center",
              "M.D. Anderson Cancer Center",
              "AstraZeneca",
              "National Cancer Institute (NCI)",
            ],
            [],
            [],
          ],
          p2_company_num: 3,
          p2_stat_company_num: [0, 1, 0, 1, 0, 1, 0, 0, 0],
          p2_company: [
            [],
            [],
            [],
            ["M.D. Anderson Cancer Center"],
            [],
            ["National Cancer Institute (NCI)"],
            ["The University of Texas MD Anderson Cancer Center"],
            [],
            [],
          ],
          p3_company_num: 1,
          p3_stat_company_num: [0, 0, 0, 0, 1, 0, 0, 0, 0],
          p3_company: [
            [],
            [],
            [],
            [],
            ["The University of Texas MD Anderson Cancer Center"],
            [],
            [],
            [],
            [],
          ],
        },
      },
    ],
  },
  {
    id: "stat3",
    label: "STAT3",
    img_path: "./logo.svg",
    tree: [
      { name: "5", parents: [], children: ["6"] },
      { name: "6", parents: ["5"], children: ["7", "8"] },
    ],
    heatsquaredata: [
      {
        label: "A",
        hvalue: 5,
        svalue: 4,
        line: [
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
          { value: 9, pub: 3 },
          { value: 10, pub: 2 },
        ],
      },
      {
        label: "B",
        hvalue: 4,
        svalue: 6,
        line: [
          { value: 3, pub: 5 },
          { value: 4, pub: 6 },
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
        ],
      },
      {
        label: "C",
        hvalue: 3,
        svalue: 7,
        line: [
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
          { value: 9, pub: 3 },
          { value: 10, pub: 2 },
        ],
      },
      {
        label: "D",
        hvalue: 6,
        svalue: 4,
        line: [
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
        ],
      },
      {
        label: "E",
        hvalue: 1,
        svalue: 5,
        line: [
          { value: 3, pub: 5 },
          { value: 4, pub: 6 },
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
        ],
      },
      {
        label: "F",
        hvalue: 2,
        svalue: 2,
        line: [
          { value: 8, pub: 4 },
          { value: 9, pub: 3 },
          { value: 10, pub: 2 },
        ],
      },
      {
        label: "G",
        hvalue: 3,
        svalue: 3,
        line: [
          { value: 3, pub: 5 },
          { value: 4, pub: 6 },
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
          { value: 9, pub: 3 },
          { value: 10, pub: 2 },
        ],
      },
      {
        label: "H",
        hvalue: 5,
        svalue: 8,
        line: [
          { value: 3, pub: 5 },
          { value: 4, pub: 6 },
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
        ],
      },
      {
        label: "I",
        hvalue: 7,
        svalue: 6,
        line: [
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
          { value: 9, pub: 3 },
          { value: 10, pub: 2 },
        ],
      },
      {
        label: "J",
        hvalue: 4,
        svalue: 3,
        line: [
          { value: 3, pub: 5 },
          { value: 4, pub: 6 },
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
          { value: 9, pub: 3 },
          { value: 10, pub: 2 },
        ],
      },
      {
        label: "K",
        hvalue: 8,
        svalue: 4,
        line: [
          { value: 3, pub: 5 },
          { value: 4, pub: 6 },
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
          { value: 9, pub: 3 },
          { value: 10, pub: 2 },
        ],
      },
      {
        label: "L",
        hvalue: 4,
        svalue: 6,
        line: [
          { value: 3, pub: 5 },
          { value: 4, pub: 6 },
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
          { value: 9, pub: 3 },
          { value: 10, pub: 2 },
        ],
      },
      {
        label: "M",
        hvalue: 5,
        svalue: 5,
        line: [
          { value: 3, pub: 5 },
          { value: 4, pub: 6 },
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
          { value: 9, pub: 3 },
          { value: 10, pub: 2 },
        ],
      },
      {
        label: "N",
        hvalue: 2,
        svalue: 6,
        line: [
          { value: 3, pub: 5 },
          { value: 4, pub: 6 },
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
          { value: 9, pub: 3 },
          { value: 10, pub: 2 },
        ],
      },
      {
        label: "O",
        hvalue: 5,
        svalue: 5,
        line: [
          { value: 3, pub: 5 },
          { value: 4, pub: 6 },
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
          { value: 9, pub: 3 },
          { value: 10, pub: 2 },
        ],
      },
      {
        label: "P",
        hvalue: 2,
        svalue: 4,
        line: [
          { value: 3, pub: 5 },
          { value: 4, pub: 6 },
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
          { value: 9, pub: 3 },
          { value: 10, pub: 2 },
        ],
      },
      {
        label: "Q",
        hvalue: 5,
        svalue: 5,
        line: [
          { value: 3, pub: 5 },
          { value: 4, pub: 6 },
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
          { value: 9, pub: 3 },
          { value: 10, pub: 2 },
        ],
      },
      {
        label: "R",
        hvalue: 2,
        svalue: 4,
        line: [
          { value: 3, pub: 5 },
          { value: 4, pub: 6 },
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
          { value: 9, pub: 3 },
          { value: 10, pub: 2 },
        ],
      },
      {
        label: "S",
        hvalue: 5,
        svalue: 5,
        line: [
          { value: 3, pub: 5 },
          { value: 4, pub: 6 },
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
          { value: 9, pub: 3 },
          { value: 10, pub: 2 },
        ],
      },
    ],
    stackedareadata: [
      {
        year: 2015,
        A: 13300,
        B: 21000,
        C: 12000,
      },
      {
        year: 2016,
        A: 32300,
        B: 42400,
        C: 21200,
      },
      {
        year: 2017,
        A: 30003,
        B: 34020,
        C: 15010,
      },
      {
        year: 2018,
        A: 12300,
        B: 22000,
        C: 11000,
      },
      {
        year: 2019,
        A: 22300,
        B: 22400,
        C: 11200,
      },
      {
        year: 2020,
        A: 12003,
        B: 20020,
        C: 10010,
      },
    ],
    detaildata: [
      {
        nodes: [
          { id: "A", group: 1, value: 1 },
          { id: "B", group: 1, value: 3 },
          { id: "C", group: 1, value: 5 },
          { id: "D", group: 2, value: 7 },
          { id: "E", group: 2, value: 4 },
          { id: "F", group: 3, value: 6 },
          { id: "G", group: 3, value: 2 },
          { id: "H", group: 4, value: 4 },
          { id: "I", group: 4, value: 8 },
          { id: "J", group: 5, value: 6 },
          { id: "K", group: 4, value: 5 },
        ],
        links: [
          { source: "A", target: "B", value: 8 },
          { source: "C", target: "D", value: 2 },
          { source: "A", target: "C", value: 2 },
          { source: "B", target: "D", value: 4 },
          { source: "A", target: "E", value: 6 },
          { source: "A", target: "F", value: 2 },
          { source: "C", target: "F", value: 1 },
          { source: "G", target: "F", value: 1 },
          { source: "G", target: "H", value: 8 },
          { source: "F", target: "I", value: 2 },
          { source: "H", target: "J", value: 3 },
          { source: "I", target: "J", value: 4 },
          { source: "J", target: "K", value: 5 },
        ],
      },
      [
        { id: "A", attr: "IC50", value: 1 },
        { id: "A", attr: "Ki", value: 0 },
        { id: "A", attr: "Kd", value: 3 },
        { id: "A", attr: "EC50", value: 2 },
        { id: "A", attr: "se", value: 5 },
        { id: "A", attr: "hERG", value: 1 },
        { id: "A", attr: "sol", value: 0 },
        { id: "B", attr: "IC50", value: 3 },
        { id: "B", attr: "Ki", value: 4 },
        { id: "B", attr: "Kd", value: 2 },
        { id: "B", attr: "EC50", value: 4 },
        { id: "B", attr: "se", value: 1 },
        { id: "B", attr: "hERG", value: 5 },
        { id: "B", attr: "sol", value: 0 },
        { id: "C", attr: "IC50", value: 1 },
        { id: "C", attr: "Ki", value: 0 },
        { id: "C", attr: "Kd", value: 3 },
        { id: "C", attr: "EC50", value: 2 },
        { id: "C", attr: "se", value: 5 },
        { id: "C", attr: "hERG", value: 1 },
        { id: "C", attr: "sol", value: 0 },
        { id: "D", attr: "IC50", value: 3 },
        { id: "D", attr: "Ki", value: 4 },
        { id: "D", attr: "Kd", value: 2 },
        { id: "D", attr: "EC50", value: 4 },
        { id: "D", attr: "se", value: 1 },
        { id: "D", attr: "hERG", value: 5 },
        { id: "D", attr: "sol", value: 0 },
        { id: "E", attr: "IC50", value: 3 },
        { id: "E", attr: "Ki", value: 4 },
        { id: "E", attr: "Kd", value: 2 },
        { id: "E", attr: "EC50", value: 5 },
        { id: "E", attr: "se", value: 6 },
        { id: "E", attr: "hERG", value: 4 },
        { id: "E", attr: "sol", value: 2 },
        { id: "F", attr: "IC50", value: 3 },
        { id: "F", attr: "Ki", value: 4 },
        { id: "F", attr: "Kd", value: 1 },
        { id: "F", attr: "EC50", value: 0 },
        { id: "F", attr: "se", value: 0 },
        { id: "F", attr: "hERG", value: 5 },
        { id: "F", attr: "sol", value: 2 },
        { id: "G", attr: "IC50", value: 3 },
        { id: "G", attr: "Ki", value: 4 },
        { id: "G", attr: "Kd", value: 2 },
        { id: "G", attr: "EC50", value: 5 },
        { id: "G", attr: "se", value: 6 },
        { id: "G", attr: "hERG", value: 4 },
        { id: "G", attr: "sol", value: 2 },
        { id: "K", attr: "IC50", value: 3 },
        { id: "K", attr: "Ki", value: 4 },
        { id: "K", attr: "Kd", value: 1 },
        { id: "K", attr: "EC50", value: 0 },
        { id: "K", attr: "se", value: 0 },
        { id: "K", attr: "hERG", value: 5 },
        { id: "K", attr: "sol", value: 2 },
      ],
      [
        { id: "A", attr: "ED50", value: 1 },
        { id: "A", attr: "t_half", value: 0 },
        { id: "A", attr: "AUC", value: 3 },
        { id: "A", attr: "bio", value: 1 },
        { id: "A", attr: "sol", value: 5 },
        { id: "C", attr: "ED50", value: 1 },
        { id: "C", attr: "t_half", value: 0 },
        { id: "C", attr: "AUC", value: 1 },
        { id: "C", attr: "bio", value: 2 },
        { id: "C", attr: "sol", value: 0 },
        { id: "D", attr: "ED50", value: 3 },
        { id: "D", attr: "t_half", value: 4 },
        { id: "D", attr: "AUC", value: 2 },
        { id: "D", attr: "bio", value: 4 },
        { id: "D", attr: "sol", value: 1 },
        { id: "G", attr: "ED50", value: 0 },
        { id: "G", attr: "t_half", value: 5 },
        { id: "G", attr: "AUC", value: 2 },
        { id: "G", attr: "bio", value: 3 },
        { id: "G", attr: "sol", value: 0 },
        { id: "K", attr: "ED50", value: 3 },
        { id: "K", attr: "t_half", value: 0 },
        { id: "K", attr: "AUC", value: 1 },
        { id: "K", attr: "bio", value: 0 },
        { id: "K", attr: "sol", value: 0 },
      ],
    ],
    sankeydata: [
      {
        name: "A",
        data: {
          p1_company_num: 8,
          p1_stat_company_num: [0, 0, 0, 3, 0, 0, 5, 0, 0],
          p1_company: [
            [],
            [],
            [],
            [
              "Barts Cancer Center, Barts and The London School of Medicine and Denistry",
              "UCSD Morres Cancer Center",
              "Tennessee Oncology",
            ],
            [],
            [],
            [
              "MedImmune LLC",
              "The University of Texas MD Anderson Cancer Center",
              "M.D. Anderson Cancer Center",
              "AstraZeneca",
              "National Cancer Institute (NCI)",
            ],
            [],
            [],
          ],
          p2_company_num: 3,
          p2_stat_company_num: [0, 1, 0, 1, 0, 1, 0, 0, 0],
          p2_company: [
            [],
            ["The University of Texas MD Anderson Cancer Center"],
            [],
            [],
            [],
            ["National Cancer Institute (NCI)"],
            ["M.D. Anderson Cancer Center"],
            [],
            [],
          ],
          p3_company_num: 1,
          p3_stat_company_num: [0, 1, 0, 0, 0, 0, 0, 0, 0],
          p3_company: [
            [],
            ["M.D. Anderson Cancer Center"],
            [],
            [],
            [],
            [],
            [],
            [],
            [],
          ],
        },
      },
      {
        name: "D",
        data: {
          p1_company_num: 8,
          p1_stat_company_num: [0, 0, 0, 3, 0, 0, 5, 0, 0],
          p1_company: [
            [],
            [],
            [],
            [
              "Barts Cancer Center, Barts and The London School of Medicine and Denistry",
              "UCSD Morres Cancer Center",
              "Tennessee Oncology",
            ],
            [],
            [],
            [
              "MedImmune LLC",
              "The University of Texas MD Anderson Cancer Center",
              "M.D. Anderson Cancer Center",
              "AstraZeneca",
              "National Cancer Institute (NCI)",
            ],
            [],
            [],
          ],
          p2_company_num: 3,
          p2_stat_company_num: [0, 1, 0, 1, 0, 1, 0, 0, 0],
          p2_company: [
            [],
            [],
            [],
            ["M.D. Anderson Cancer Center"],
            [],
            ["National Cancer Institute (NCI)"],
            ["The University of Texas MD Anderson Cancer Center"],
            [],
            [],
          ],
          p3_company_num: 1,
          p3_stat_company_num: [0, 0, 0, 0, 1, 0, 0, 0, 0],
          p3_company: [
            [],
            [],
            [],
            [],
            ["The University of Texas MD Anderson Cancer Center"],
            [],
            [],
            [],
            [],
          ],
        },
      },
    ],
  },
  {
    id: "a",
    label: "a",
    img_path: "./logo.svg",
    tree: [
      { name: "2", parents: ["1"], children: ["4"] },
      { name: "4", parents: ["2"], children: [] },
    ],
    heatsquaredata: [
      { label: "A", hvalue: 5, svalue: 2 },
      { label: "B", hvalue: 4, svalue: 1 },
      { label: "C", hvalue: 3, svalue: 4 },
      { label: "D", hvalue: 6, svalue: 5 },
      { label: "E", hvalue: 1, svalue: 3 },
      { label: "F", hvalue: 2, svalue: 5 },
      { label: "G", hvalue: 3, svalue: 8 },
      { label: "H", hvalue: 5, svalue: 5 },
      { label: "I", hvalue: 7, svalue: 4 },
      { label: "J", hvalue: 4, svalue: 5 },
      { label: "K", hvalue: 8, svalue: 2 },
      { label: "L", hvalue: 4, svalue: 3 },
      { label: "M", hvalue: 5, svalue: 1 },
      { label: "N", hvalue: 2, svalue: 5 },
      { label: "O", hvalue: 5, svalue: 5 },
      { label: "P", hvalue: 2, svalue: 4 },
      { label: "Q", hvalue: 5, svalue: 5 },
      { label: "R", hvalue: 2, svalue: 4 },
      { label: "S", hvalue: 5, svalue: 5 },
    ],
    stackedareadata: [
      {
        year: 2015,
        A: 13300,
        B: 21000,
        C: 12000,
      },
      {
        year: 2016,
        A: 32300,
        B: 42400,
        C: 21200,
      },
      {
        year: 2017,
        A: 30003,
        B: 34020,
        C: 15010,
      },
      {
        year: 2018,
        A: 12300,
        B: 22000,
        C: 11000,
      },
      {
        year: 2019,
        A: 22300,
        B: 22400,
        C: 11200,
      },
      {
        year: 2020,
        A: 12003,
        B: 20020,
        C: 10010,
      },
    ],
  },
  {
    id: "b",
    label: "b",
    img_path: "./logo.svg",
    tree: [
      { name: "6", parents: ["5"], children: ["7", "8"] },
      { name: "7", parents: ["6"], children: [] },
      { name: "8", parents: ["6"], children: [] },
    ],
    heatsquaredata: [
      { label: "A", hvalue: 5, svalue: 3 },
      { label: "B", hvalue: 4, svalue: 4 },
      { label: "C", hvalue: 3, svalue: 5 },
      { label: "D", hvalue: 6, svalue: 6 },
      { label: "E", hvalue: 1, svalue: 2 },
      { label: "F", hvalue: 2, svalue: 4 },
      { label: "G", hvalue: 3, svalue: 6 },
      { label: "H", hvalue: 5, svalue: 4 },
      { label: "I", hvalue: 7, svalue: 5 },
      { label: "J", hvalue: 4, svalue: 3 },
      { label: "K", hvalue: 8, svalue: 4 },
      { label: "L", hvalue: 4, svalue: 3 },
      { label: "M", hvalue: 5, svalue: 6 },
      { label: "N", hvalue: 2, svalue: 4 },
      { label: "O", hvalue: 5, svalue: 5 },
      { label: "P", hvalue: 2, svalue: 4 },
      { label: "Q", hvalue: 5, svalue: 5 },
      { label: "R", hvalue: 2, svalue: 4 },
      { label: "S", hvalue: 5, svalue: 5 },
    ],
    stackedareadata: [
      {
        year: 2015,
        A: 13300,
        B: 21000,
        C: 12000,
      },
      {
        year: 2016,
        A: 32300,
        B: 42400,
        C: 21200,
      },
      {
        year: 2017,
        A: 30003,
        B: 34020,
        C: 15010,
      },
      {
        year: 2018,
        A: 12300,
        B: 22000,
        C: 11000,
      },
      {
        year: 2019,
        A: 22300,
        B: 22400,
        C: 11200,
      },
      {
        year: 2020,
        A: 12003,
        B: 20020,
        C: 10010,
      },
    ],
  },
  {
    id: "c",
    label: "c",
    img_path: "./logo.svg",
    tree: [
      { name: "3", parents: ["1"], children: ["9", "10", "11"] },
      { name: "9", parents: ["3"], children: [] },
      { name: "10", parents: ["3"], children: [] },
    ],
    heatsquaredata: [
      {
        label: "A",
        hvalue: 5,
        svalue: 4,
        line: [
          { value: 3, pub: 5 },
          { value: 4, pub: 6 },
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
          { value: 9, pub: 3 },
          { value: 10, pub: 2 },
        ],
      },
      {
        label: "B",
        hvalue: 4,
        svalue: 3,
        line: [
          { value: 2, pub: 3 },
          { value: 3, pub: 4 },
          { value: 4, pub: 5 },
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 4 },
          { value: 8, pub: 5 },
          { value: 9, pub: 3 },
          { value: 10, pub: 2 },
        ],
      },
      {
        label: "C",
        hvalue: 3,
        svalue: 5,
        line: [
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
          { value: 9, pub: 3 },
          { value: 10, pub: 2 },
        ],
      },
      {
        label: "D",
        hvalue: 6,
        svalue: 7,
        line: [
          { value: 3, pub: 5 },
          { value: 4, pub: 10 },
          { value: 5, pub: 9 },
          { value: 6, pub: 4 },
          { value: 7, pub: 2 },
        ],
      },
      {
        label: "E",
        hvalue: 1,
        svalue: 4,
        line: [
          { value: 3, pub: 5 },
          { value: 4, pub: 6 },
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
          { value: 9, pub: 3 },
          { value: 10, pub: 2 },
        ],
      },
      {
        label: "F",
        hvalue: 2,
        svalue: 3,
        line: [
          { value: 3, pub: 5 },
          { value: 4, pub: 6 },
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
          { value: 9, pub: 3 },
          { value: 10, pub: 2 },
        ],
      },
      {
        label: "G",
        hvalue: 3,
        svalue: 2,
        line: [
          { value: 3, pub: 5 },
          { value: 4, pub: 6 },
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
          { value: 9, pub: 3 },
          { value: 10, pub: 2 },
        ],
      },
      {
        label: "H",
        hvalue: 5,
        svalue: 5,
        line: [
          { value: 3, pub: 5 },
          { value: 4, pub: 6 },
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
          { value: 9, pub: 3 },
          { value: 10, pub: 2 },
        ],
      },
      {
        label: "I",
        hvalue: 7,
        svalue: 7,
        line: [
          { value: 3, pub: 5 },
          { value: 4, pub: 6 },
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
          { value: 9, pub: 3 },
          { value: 10, pub: 2 },
        ],
      },
      {
        label: "J",
        hvalue: 4,
        svalue: 8,
        line: [
          { value: 3, pub: 5 },
          { value: 4, pub: 6 },
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
          { value: 9, pub: 3 },
          { value: 10, pub: 2 },
        ],
      },
      {
        label: "K",
        hvalue: 8,
        svalue: 9,
        line: [
          { value: 3, pub: 5 },
          { value: 4, pub: 6 },
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
          { value: 9, pub: 3 },
          { value: 10, pub: 2 },
        ],
      },
      {
        label: "L",
        hvalue: 4,
        svalue: 5,
        line: [
          { value: 3, pub: 5 },
          { value: 4, pub: 6 },
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
          { value: 9, pub: 3 },
          { value: 10, pub: 2 },
        ],
      },
      {
        label: "M",
        hvalue: 5,
        svalue: 3,
        line: [
          { value: 3, pub: 5 },
          { value: 4, pub: 6 },
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
          { value: 9, pub: 3 },
          { value: 10, pub: 2 },
        ],
      },
      {
        label: "N",
        hvalue: 2,
        svalue: 5,
        line: [
          { value: 3, pub: 5 },
          { value: 4, pub: 6 },
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
          { value: 9, pub: 3 },
          { value: 10, pub: 2 },
        ],
      },
      {
        label: "O",
        hvalue: 5,
        svalue: 5,
        line: [
          { value: 3, pub: 5 },
          { value: 4, pub: 6 },
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
          { value: 9, pub: 3 },
          { value: 10, pub: 2 },
        ],
      },
      {
        label: "P",
        hvalue: 2,
        svalue: 4,
        line: [
          { value: 3, pub: 5 },
          { value: 4, pub: 6 },
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
          { value: 9, pub: 3 },
          { value: 10, pub: 2 },
        ],
      },
      {
        label: "Q",
        hvalue: 5,
        svalue: 5,
        line: [
          { value: 3, pub: 5 },
          { value: 4, pub: 6 },
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
          { value: 9, pub: 3 },
          { value: 10, pub: 2 },
        ],
      },
      {
        label: "R",
        hvalue: 2,
        svalue: 4,
        line: [
          { value: 3, pub: 5 },
          { value: 4, pub: 6 },
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
          { value: 9, pub: 3 },
          { value: 10, pub: 2 },
        ],
      },
      {
        label: "S",
        hvalue: 5,
        svalue: 5,
        line: [
          { value: 3, pub: 5 },
          { value: 4, pub: 6 },
          { value: 5, pub: 8 },
          { value: 6, pub: 9 },
          { value: 7, pub: 10 },
          { value: 8, pub: 4 },
          { value: 9, pub: 3 },
          { value: 10, pub: 2 },
        ],
      },
    ],
    stackedareadata: [
      {
        year: 2015,
        A: 13300,
        B: 21000,
        C: 12000,
      },
      {
        year: 2016,
        A: 32300,
        B: 42400,
        C: 21200,
      },
      {
        year: 2017,
        A: 30003,
        B: 34020,
        C: 15010,
      },
      {
        year: 2018,
        A: 12300,
        B: 22000,
        C: 11000,
      },
      {
        year: 2019,
        A: 22300,
        B: 22400,
        C: 11200,
      },
      {
        year: 2020,
        A: 12003,
        B: 20020,
        C: 10010,
      },
    ],
  },
  {
    id: "d",
    label: "d",
    img_path: "./logo.svg",
    tree: [
      { name: "3", parents: ["1"], children: ["9", "10", "11"] },
      { name: "11", parents: ["3"], children: ["12"] },
      { name: "12", parents: ["11"], children: [] },
    ],
    heatsquaredata: [
      { label: "A", hvalue: 5, svalue: 2 },
      { label: "B", hvalue: 4, svalue: 4 },
      { label: "C", hvalue: 3, svalue: 5 },
      { label: "D", hvalue: 6, svalue: 6 },
      { label: "E", hvalue: 1, svalue: 4 },
      { label: "F", hvalue: 2, svalue: 8 },
      { label: "G", hvalue: 3, svalue: 3 },
      { label: "H", hvalue: 5, svalue: 4 },
      { label: "I", hvalue: 7, svalue: 5 },
      { label: "J", hvalue: 4, svalue: 1 },
      { label: "K", hvalue: 8, svalue: 3 },
      { label: "L", hvalue: 4, svalue: 2 },
      { label: "M", hvalue: 5, svalue: 5 },
      { label: "N", hvalue: 2, svalue: 5 },
      { label: "O", hvalue: 5, svalue: 5 },
      { label: "P", hvalue: 2, svalue: 4 },
      { label: "Q", hvalue: 5, svalue: 5 },
      { label: "R", hvalue: 2, svalue: 4 },
      { label: "S", hvalue: 5, svalue: 5 },
    ],
    stackedareadata: [
      {
        year: 2015,
        A: 13300,
        B: 21000,
        C: 12000,
      },
      {
        year: 2016,
        A: 32300,
        B: 42400,
        C: 21200,
      },
      {
        year: 2017,
        A: 30003,
        B: 34020,
        C: 15010,
      },
      {
        year: 2018,
        A: 12300,
        B: 22000,
        C: 11000,
      },
      {
        year: 2019,
        A: 22300,
        B: 22400,
        C: 11200,
      },
      {
        year: 2020,
        A: 12003,
        B: 20020,
        C: 10010,
      },
    ],
  },
];

export default target_data;
